### ISSUE TITLE
Outposts icons are sometimes not displayed

### ISSUE THREAD

**Issue by PainOchoco** [TownyAdvanced/MapTowny#39] opened 2022-11-26 12:09 UTC
## Expected Behavior

Flag icons on squaremap are sometimes not displayed.

Here's an example, one of these claims is an outpost but there's no flag on top of it.
![image](https://user-images.githubusercontent.com/47084457/204087881-e4510f9d-2d13-4582-9fec-3fe56c75b9bf.png)
![image](https://user-images.githubusercontent.com/47084457/204087897-3b76223a-312a-4397-9efe-c42a30001207.png)

It should have a flag on the map like this outpost :
![image](https://user-images.githubusercontent.com/47084457/204088126-d9c9d2ed-3d80-4f92-8f49-88e98bd17229.png)

### Plugin Version

2.0.0
### Towny Version
0.98.3.11
### Squaremap Version
1.1.6
### Server Software Version

git-Purpur-1708 (MC: 1.19)

**Comment by silverwolfg11** [comment] 2024-01-25 05:29
Closing this as a duplicate of #52 (more recent).

**Closed by silverwolfg11** 2024-01-25 05:29 UTC
Labels: bug
